### ISSUE TITLE
执行yarn dev:h5报错

### ISSUE THREAD

**Issue by CatchMeX** [weilaiqishi/lowcode-designable-taro-react#3]
package.json里是不是少了一个依赖 执行yarn dev:h5会报这个错
<img width="1041" alt="image" src="https://github.com/weilaiqishi/lowcode-designable-taro-react/assets/127017279/a3104126-0f48-4021-a2e7-b49c1ec64297">

**Comment by CatchMeX** [comment]
然后安装了 @tarojs/plugin-platform-h5这个包后  执行yarn dev:h5 又报这个错
<img width="1337" alt="image" src="https://github.com/weilaiqishi/lowcode-designable-taro-react/assets/127017279/6df790ac-76d9-4687-a46d-c6a203b15de8">
这是为什么阿 求大佬帮忙解决

**Comment by weilaiqishi** [comment]
这个项目是依赖taro3.5版本的，taro3.6我看看能不能更新。
这个项目还是一个monorepo，如果可以接受taro3.5版本，可以试一下按readme或下述步骤运行

1.依赖安装
根目录下

```bash
npm i -g yarn lerna@6.6.2 ts-node @tarojs/cli@3.6.7
lerna bootstrap
```

2.物料组件库打包
taroify-formily 目录下

```bash
yarn build
```

3.Taro Demo运行h5预览
taroify-formily-demo 目录下

```bash
yarn dev:h5
```

`taroify-formily-demo/src/pages/index/jsonSchema.json`
可以替换 `PC端可视化设计器` 中编辑好的json

4.可视化设计器启动
taroify-formily-designable 目录下
`taroify-formily-designable/start.js` 中可修改步骤3中 `Taro Demo` 本地服务地址

```bash
yarn start
```

**Comment by CatchMeX** [comment]
可是第三步 yarn dev:h5的编译不是需要@tarojs/plugin-platform-h5 这个依赖吗 我看package.json 里没有这个依赖 导致yarn dev:h5的时候会报错：找不到插件依赖 "@tarojs/plugin-platform-h5"，请先在项目中安装 您那边没有这个h5的依赖 也可以跑起来吗?

**Comment by weilaiqishi** [comment]
> 可是第三步 yarn dev:h5的编译不是需要@tarojs/plugin-platform-h5 这个依赖吗 我看package.json 里没有这个依赖 导致yarn dev:h5的时候会报错：找不到插件依赖 "@tarojs/plugin-platform-h5"，请先在项目中安装 您那边没有这个h5的依赖 也可以跑起来吗?

试一下把全局依赖@tarojs/cli降低到3.5.11版本

**Comment by CatchMeX** [comment]
ok

**Comment by CatchMeX** [comment]
感谢感谢 可以了 难怪我install plugin-platform-h5 这个依赖的时候 最早的版本都是3.6.x的版本 原来taro 3.5 根本就没有这个包 不过我全局的taro版本是3.6的时候 我有试过通过安装plugin-platform-h5这个依赖 编译h5代码 但是会报错 好像看起来是因为plugin-platform-h5这个包 和虚拟列表相关的包 兼容性上有问题 版本或者其他问题不一致导致的 估计要升级taro最新版本 还得费些功夫 感谢帮我解决问题

**Comment by weilaiqishi** [comment]
可以试一下本项目taro3.6分支

**Comment by CatchMeX** [comment]
好的
