### ISSUE TITLE
在nutui-react-taro分支下运行mobile会报错

### ISSUE THREAD

**Issue by guoxf** [weilaiqishi/lowcode-designable-taro-react#4]
运行环境：Windows11+nodej18
错误如下：

ERROR in ../../node_modules/.pnpm/@kimeng+vm@0.6.0_@babel+core@7.24.4_typescript@5.4.5_webpack@5.91.0/node_modules/@kimeng/vm/src/vm.ts 18:6
Module parse failed: Unexpected token (18:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export function runInContext(
>   code: string,
|   context: Context,
|   preset: presetMap = presetMap.env

**Comment by weilaiqishi** [comment]
已修复
调整了Taro项目需要进过编译的文件配置
有一个JS解释器需要进行编译，原来的路径判断没兼容pnpm

```
     compile: {
-      include: [path.resolve(__dirname, '..', '..', 'ui'), (modulePath) => modulePath.includes('@kimeng/vm')]
+      include: [path.resolve(__dirname, '..', '..', 'ui'), (modulePath) => {
+        const isIncludes = modulePath.includes('@kimeng/vm') || modulePath.includes('@kimeng+vm')
+        return isIncludes
+      }]
     }
```
